### ISSUE TITLE
Queued (Pending) Notifications are never sent

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#192]
I was testing Comment Mail Lite v151224 after importing StCR subscriptions when I tried posting two new replies to existing comments with subscriptions (i.e., I posted new replies to comments that had StCR subscriptions, which were imported into Comment Mail). The new Comment Mail subscriptions were created fine, and were connected to the appropriate imported StCR subscription, however the notifications for those new replies were never sent.

Looking at the Mail Queue, I noticed the two notifications were sitting there, unsent:

![2015-12-26_09-37-26](https://cloud.githubusercontent.com/assets/53005/12006838/a520fa92-abb5-11e5-8107-3b667ab6d318.png)

Notice the time on them... it had been ~45 minutes since the notifications were created and they still have not been sent. Here's what I tried to get the email queue to be processed:
- Tried manually running the `_cron_comment_mail_queue_processor` event
- Tried disabling the two email-related plugins that I had installed (**WP Mail SMTP** and **Email Log**) and then manually running the `_cron_comment_mail_queue_processor` event.
- Tried disabling/enabling Comment Mail
- Tried disabling Mail Queue Processing in **Comment Mail → Config. Options → Enable/Disable** and then enabling it again.

None of these things helped. The queued notifications remained queued and were not sent out.

Also, my PHP error log did not report any errors during this time.

**Comment by raamdev** [comment]
Note: I **don't** believe this is related to https://github.com/websharks/comment-mail/issues/194 (_Cron event disappears in some scenarios: `_cron_comment_mail_queue_processor`_) because as noted above the notifications in the queue would not send **even when I was able to manually run the `_cron_comment_mail_queue_processor` event**.

**Comment by jaswsinc** [comment]
> None of these things helped. The queued notifications remained queued and were not sent out.

Also try looking at the Queue Event Log to see if anything turns up there after you run the queue processor. If they were not processed that should show up in the log as having been invalidated for some reason. Also be sure to look over the available Screen Options in the Queue Event Log, because there is a lot of information available there if you tell WordPress to expose it.

Also referencing: https://github.com/websharks/comment-mail-pro/blob/151224/comment-mail-pro/includes/classes/queue-processor.php#L503

**Comment by raamdev** [comment]
@jaswsinc The Queue Event Log shows nothing:

![2015-12-29_12-29-17](https://cloud.githubusercontent.com/assets/53005/12038632/c9281f46-ae27-11e5-851d-e6b6a0bdb9ec.png)

**Comment by raamdev** [comment]
@kristineds @renzms @Reedyseth I could use some help attempting to reproduce the issue described above. :smile:

**Comment by renzms** [comment]
@raamdev 

Under my Events list it says `notified`, but I may need to replicate it exactly as you did by using a fresh install of Comment Mail Lite v151224 right after using StCR subscribe and to import users. 

I imported users from StCR a week ago, and the Comment Mail subscriptions were working as normal.

**Comment by raamdev** [comment]
@renzms Any more progress on testing this one?

**Comment by renzms** [comment]
@raamdev 

- Started over from a clean version. 
- Installed Comment Mail Lite v151224 
- Used same subscribers from StCR import
- Added new comments and replies
- Notifications were sent (some went to Spam, but that's probably SMTP related)
- Wasn't able to replicate what you experienced.

![screen shot 2016-01-15 at 3 46 23 pm](https://cloud.githubusercontent.com/assets/13220018/12348123/32a05e82-bb9f-11e5-99bc-c8608379cb47.png)

@kristineds @Reedyseth Could you guys please try as well and see if you can replicate what Raam has noted?

**Comment by kristineds** [comment]
@raamdev: Tested this but wasn't able to reproduce the issue you pointed out.

- Installed Comment Mail Lite v151224 + WP v.4.4.1 + StCR v160115 on a clean install
- Successfully imported StCR subscribers
- Posted new replies to comments that had StCR subscriptions, which were imported into Comment Mail
- Notifications were sent according to the Comment Mail  Queue Event Log 

![Comment Mail  Queue Event Log](https://cloud.githubusercontent.com/assets/7514953/12356608/7ce5292a-bbde-11e5-967a-ec3a6f2e4824.png)

- No unsent notifications (nothing under Queued (Pending) Notifications)

![Queued (Pending) Notifications](https://cloud.githubusercontent.com/assets/7514953/12356637/a5fa0c40-bbde-11e5-953e-19131c43aa90.png)

**Comment by raamdev** [comment]
@renzms @kristineds Thanks so much for testing this some more. I'm going to close this as `cannot reproduce` for now. I was seeing this on my personal raam.org site where there are several other plugins running, so it sounds like what I was seeing might be related to a plugin conflict.

I'll come back and reopen this if I'm able to reproduce it. :smile:

**Comment by raamdev** [comment]
Reopening. Also reported here: https://wordpress.org/support/topic/why-are-some-emails-awaiting-processing?replies=1

**Comment by lucashall** [comment]
Hi @raamdev,

Thanks for trying to help.

I'm seeing this same issue. Some comments are getting through, others are getting stuck in processing. 

The site is https://landlordology.com 

The odd thing is that some emails are getting stuck, while others are getting through.  Here's the Pending Queue vs the Log.

![screenshot 2016-02-14 13 06 59](https://cloud.githubusercontent.com/assets/6332983/13035729/774528be-d324-11e5-8ae9-4678f3a43232.png)

![screenshot 2016-02-14 13 06 59](https://cloud.githubusercontent.com/assets/6332983/13035730/79134270-d324-11e5-9213-247794288a4c.png)

Here's the configuration:
- WP 4.4.1
- StCR Version 160115
- Comment Mail Version 151224

I followed the instructions on importing users from StCR.

Here are the active plugins:
- Akismet
- Amazon Web Services
- Analytics for WordPress — by Segment.io
- Blubrry PowerPress
- Broken Link Checker
- Comment Mail
- Comment Redirect by Yoast
- Display Posts Shortcode
- Display Widgets
- Duplicate Post
- DW PromoBar
- Easy Social Share Buttons for WordPress
- Gravity Forms
- Gravity Forms Slack Add-On
- Gravity Forms Stripe Add-On
- Gravity Forms User Registration Add-On
- Gravity Forms Zapier Add-on
- GravityView
- GravityView - A-Z Filters Extension
- GravityView - Advanced Filter Extension
- GravityView - DataTables Extension
- GravityView - Featured Entries Extension
- Greg's Comment Length Limiter
- Jetpack by WordPress.com
- Login Logo
- MapSVG
- Newsletter Sign-Up
- OptinMonster
- OptinMonster - After Post Addon
- OptinMonster - Canvas Addon
- OptinMonster - Exit Intent Addon
- Q2W3 Fixed Widget
- Scroll Triggered Box
- Simple Preview
- Simple URLs
- Smart Podcast Player
- TablePress
- WP fail2ban
- WP Offload S3
- Yet Another Related Posts Plugin
- Yoast SEO

**Comment by lucashall** [comment]
Hi @raamdev 

Just wanted to circle back to this.  I've finding that the emails that get stuck as "awaiting processing" are getting sent roughly 19 days later.  What can I do to help with this issue?

**Comment by raamdev** [comment]
> the emails that get stuck as "awaiting processing" are getting sent roughly 19 days later.

@lucashall That's really interesting. @jaswsinc any thoughts on what might be causing this?

**Comment by raamdev** [comment]
@jaswsinc Ping. ↑

**Comment by raamdev** [comment]
Also reported here: https://wordpress.org/support/topic/sparkpost-and-asynchronous-mail?replies=7#post-8466772

**Comment by jaswsinc** [comment]
Nothing jumping right out at me yet, sorry. I'm going to do some digging as I outline some of the logic behind the software for others in a video soon, and I'll keep this in mind so that we can get to the bottom of it by running diagnostics on sub-routines in the queue processor.

It may also help if we implement some debug logging routines in the queue processor whenever `WP_DEBUG` mode is enabled so that a site owner reporting problems like this will be able to copy/paste something for us privately that might shed more light.

**Comment by bobinoz** [comment]
Hi everyone

Continuing the conversation on from the WordPress support page via the link you have already just posted raamdev, here is an up-to-date list of my active plug-ins:

Akismet
Anti-spam
BackupBuddy
Better WordPress Minify
Cron Gui
Easy Digital Downloads
Google Analytics Dashboard for WP
Google XML Site Map for Videos
Jetpack by WordPress.com
Jetpack lite
Maintenance Mode
MaxBlogPress Ping Optimizer
neuvoo jobroll
No Self Pings
Ozh' Admin Drop-Down Menu
P3 Plug-In Performance Profiler
Post Plug-In Library
Redirection
Reenable Shortlink Item In Admin Toolbar
Related Posts Thumbnails
Remember Me Controls
Revision Cleaner
S3FlowShield
SEO Friendly Images
Simple Social Icons
Social Share Bar (Digg Digg Alternative)
SparkPost
Tako Movable Comments
Ultimate Category Excluder
What Would Seth Godin Do
WordPress Popular Posts
WordPress PopUp
WordPress.com Popular Posts
WP Missed Schedule
WPtouch Mobile Plugin
Youtube Not Found

As you can see, I only have Akismet and Jetpack by WordPress.com in common with lucashall's plug-in list, for what it's worth though I also have Broken Link Checker installed but deactivated. What I do seem to have in common with lucashall's website though is large numbers of comments, the test I ran which produced this error was posting a reply on a page with around 1500 comments and about 100 subscribers.

My website is http://www.bobinoz.com/ running WordPress version 4.5.2 and Thesis theme 2.2.

Thanks, Bob

**Comment by raamdev** [comment]
So far the only active plugins that are common to the three people experiencing this (myself, @lucashall, and @bobinoz) are Akismet and JetPack for WordPress.com.

That makes me wonder if this issue is related to a specific JetPack module.

Here's my list of active JetPack modules:

- Custom CSS
- Enhanced Distribution
- Extra Sidebar Widgets
- JSON API
- Likes
- Manage
- Markdown
- Notifications
- Omnisearch
- Post by Email
- Protect
- Publicize
- Shortcode Embeds
- Sharing
- Site Stats
- Site Verification
- Spelling and Grammar
- Widget Visibility

@lucashall @bobinoz Would you mind listing your active JetPack modules? (See **JetPack → Settings**.)

**Comment by bobinoz** [comment]
Well, I think I might be able to make this bit of the process easier, I only have two of their modules active.

- Site Stats
- WP.Me Shortlinks

As you can see from my list, I also use Jetpack Lite which I think I installed to prevent Jetpack from automatically loading up more modules.

I assume from your response that you have completely discounted the number of comments/subscribers as being the issue?

**Comment by raamdev** [comment]
@bobinoz writes...
> I assume from your response that you have completely discounted the number of comments/subscribers as being the issue?

No, certainly not. That's a definite possibility. On my personal site I have over 1,000 StCR subscriptions that I imported into Comment Mail and when I tried posting new replies to comments associated with an imported StCR subscription, that's when I saw the issue with "Awaiting processing".

How many StCR subscriptions did you import?

@lucashall If you could tell us how many StCR subscriptions you imported, that would be helpful as well.

**Comment by bobinoz** [comment]
Well, for me it was just over 4000 subscriptions that I imported from StCR and I think lucashall had quite a big database, because he had 3000 stuck in the "awaiting processing" queue and he said it was a large blog. That's why I was thinking maybe it is the numbers.

**Comment by lucashall** [comment]
Hi All,

If this is helpful, I have approx 4300 subscriptions on landlordology.com


Best,
*Lucas Hall*

Head of Industry Relations, Cozy | cozy.co | @CozyCo
<https://twitter.com/CozyCo>
Founder of Landlordology | landlordology.com <http://www.landlordology.com/> |
@Landlordology <https://twitter.com/Landlordology>

**Comment by raamdev** [comment]
@bobinoz @lucashall Thank you. 4,000+ and 3,000+ StCR subscriptions. Coupling that with my (measly!) 1,000 subscriptions, I'd say there's a good chance the bug here is related to the large number of StCR subscriptions being imported.

@kristineds @renzms I could use some help here. 

The next step is to start attempting to reproduce this bug on a test site with a large (2,000+) number of existing StCR subscriptions and then see if Comment Mail has a problem sending notifications after an import. (See my first post in this issue for a description of the problem.

@jaswsinc Any new thoughts come to mind about this issue given the new information above?

**Comment by jaswsinc** [comment]
@raamdev Here's a video I did that might help you debug this: https://youtu.be/I0TnFBcasoU

**Comment by raamdev** [comment]
@jaswsinc While testing v160611-RC, I was able to reproduce this issue again on my personal site, where I'm currently using StCR. To recap, here's what I did:

1. Before installing Comment Mail, I posted a couple of comments on an existing post with various configurations (i.e., replies only, all replies, no subscription) and confirmed the StCR created the subscriptions properly and that StCR was sending the notifications to subsequent replies as expected.
1. I then installed and activated Comment Mail Lite v160611-RC.
1. I deactivated the StCR plugin.
1. I enabled Comment Mail.
1. I ran the StCR importer and confirmed that all of my test subscriptions were imported as expected (they were).
1. To test that Comment Mail would now send notifications to those imported StCR subscriptions, I left a few more replies to those existing comments. When I took a look at the Mail Queue, I saw exactly what I reported at the top of this GitHub issue:
     
     ![2016-06-14_15-55-53](https://cloud.githubusercontent.com/assets/53005/16057522/871f428c-3248-11e6-9da5-c2327e48312d.png)

1. I then took a look at the `wp_comment_mail_queue` table in the database as you suggested in your video; the `hold_until_time` shows a `0` value for both rows:

     ![2016-06-14_15-50-46](https://cloud.githubusercontent.com/assets/53005/16057370/c9ee1576-3247-11e6-847c-a194ca4327b4.png)

1. I installed WP Crontrol and confirmed that the `_cron_comment_mail_queue_processor` cron event was present. I also waited two entire 5-minute cycles, pressing refresh over and over on the Mail Queue page. The notifications in the queue were never sent.

![2016-06-14_15-58-25](https://cloud.githubusercontent.com/assets/53005/16057685/2f566926-3249-11e6-8ed7-7d11ab3bdd0a.png)

1. I confirmed that the Mail Queue Processor and Comment Mail were enabled all this time:

![2016-06-14_15-58-04](https://cloud.githubusercontent.com/assets/53005/16057683/2d47754e-3249-11e6-9dc1-e6ae8072ba28.png)

----

Any ideas for what to try next? 😄

**Comment by raamdev** [comment]
Since I'm running Akismet and JetPack for WordPress.com, the two plugins in common with @bobinoz and @lucashall as noted above, I tried disabling both of those on my personal site to see if that might get the Mail Queue Processor to run and pick up those two stuck notifications: No such luck.

**Comment by jaswsinc** [comment]
@raamdev Thank you. If you still have that available can you post a screenshot of the database rows for `sub_id` `966` and `967` for me? i.e., those that match the queue entries in your screenshot above.

**Comment by raamdev** [comment]
@jaswsinc writes...
> can you post a screenshot of the database rows for sub_id 966 and 967 for me?

Here you go:

![2016-06-15_22-46-47](https://cloud.githubusercontent.com/assets/53005/16103974/2f25ceb2-334b-11e6-91cc-dd20454230fb.png)

**Comment by jaswsinc** [comment]
This just looks like the CRON is not actually running for some reason. I'll take a wild guess and blame this on WP Crontrol for now, but I'm going to run some tests of my own shortly to see why/how WP Crontrol seems to not work when it comes to Comment Mail.

**Comment by raamdev** [comment]
@jaswsinc writes...
> I'll take a wild guess and blame this on WP Crontrol for now,

But, why? I'm not using WP Crontrol to run the cron job... and if I deactivate WP Crontrol, I still have the same issue...

**Comment by jaswsinc** [comment]
At the moment, the only explanation I can come up with for this is that the queue processor is simply not running. All of my tests indicate that if it was, this simply would not be the case; i.e., they shouldn't just sit in the queue if the queue processor is running, because the point of it running is to clear these out of the queue. The `hold_until_time` is `0` indicating that these entries have never been processed.

So in order to narrow it down and try to prove that theory, we need to make absolutely sure the queue processor is in fact running via CRON as it's supposed to. The only way to force this to occur at the moment is via WP Crontrol. If that's failing also, then this is becoming a more difficult mystery to solve.

---

If these are still just sitting in the queue you can try to attach a custom log routine of your own so that you can prove that it's running and failing, or find out if it's simply not running at all.

After [this line](https://github.com/websharks/comment-mail-pro/blob/000000-dev/src/includes/classes/QueueProcessor.php#L204) try something like this and monitor the log file.

```php
file_put_contents(WP_CONTENT_DIR.'/cm-queue-debug.log', print_r($_REQUEST, true)."\n\n", FILE_APPEND);
```

**Comment by raamdev** [comment]
@jaswsinc After watching the `_cron_comment_mail_queue_processor` cron event (from inside WP Crontrol) count down and run on schedule, I find the following in the log file:

```
$ cat cm-queue-debug.log
Array
(
    [doing_wp_cron] => 1466046615.4939270019531250000000
)
```

**Comment by raamdev** [comment]
@jaswsinc I've narrowed down the issue to a problem with [`entryMessage()`](https://github.com/websharks/comment-mail-pro/blob/160611-RC/src/includes/classes/QueueProcessor.php#L888). Something is happening on [this line](https://github.com/websharks/comment-mail-pro/blob/160611-RC/src/includes/classes/QueueProcessor.php#L262) that is causing a silent failure.

I'm suspecting this might have something to do with the fact that I'm seeing stuff related to RVE (Replies via Email) in the `entryMessage()` method, and I'm testing this on Comment Mail Lite, which doesn't have that feature. However, the `src/includes/classes/UtilsRve.php` file _does_ currently exist in the Lite version of v160611-RC (it probably shouldn't...right?)

**Comment by raamdev** [comment]
> I'm seeing stuff related to RVE

Scratch that. I see that we're specifically checking `if ($this->plugin->options['replies_via_email_enable'])`.

Now looking more closely at [`parse()`](https://github.com/websharks/comment-mail-pro/blob/160611-RC/src/includes/classes/Template.php#L132).

**Comment by jaswsinc** [comment]
> After watching the _cron_comment_mail_queue_processor cron event (from inside WP Crontrol) count down and run on schedule, I find the following in the log file:

So it _is_ running then. Hmm. The plot thickens.

> Now looking more closely at parse().

Cool. Really curious to know how this happens.

**Comment by raamdev** [comment]
@jaswsinc Something is going on in [this `evaluate()`](https://github.com/websharks/comment-mail-pro/blob/160611-RC/src/includes/classes/UtilsPhp.php#L71) method... any debugging suggestions for that? 😁

**Comment by raamdev** [comment]
I've confirmed there's nothing wrong with `if ($this->isPossible('eval'))`, i.e., `eval` IS possible, so it's not that... my only thought is that this has something to do with the output buffering that is being used there.

**Comment by jaswsinc** [comment]
> Something is going on in this evaluate() method... 

What indication do you have there is a problem?
Just curious to know what the symptom is so I can help debug.

**Comment by raamdev** [comment]
@jaswsinc Since this is on my live site where I don't have xdebug (and since I can't seem to reproduce this in a separate test install), I'm just adding logging routines (like the one you gave me above) to follow the code and try to figure out at what point things "fail". 

In the `parse()` method, I changed [this line](https://github.com/websharks/comment-mail-pro/blob/160611-RC/src/includes/classes/Template.php#L149) to the following:

```php
        file_put_contents(WP_CONTENT_DIR.'/cm-queue-debug.log', "INSIDE parse() BEFORE passing evaluate()\n\n", FILE_APPEND);
        $var = trim($this->plugin->utils_php->evaluate($this->file_contents, $vars));
        file_put_contents(WP_CONTENT_DIR.'/cm-queue-debug.log', "INSIDE parse() AFTER passing evaluate()\n\n", FILE_APPEND);
        return $var;
```

I would expect that every time I pass something to `evaluate()` I will see a BEFORE and an AFTER log entry, however the log always ends with a BEFORE entry and no AFTER entry, indicating to me that something went wrong in there...

(The first `entryMessage() passing to parse()` entry is where I added a logging routine to [this line in `entryMessage()`](https://github.com/websharks/comment-mail-pro/blob/160611-RC/src/includes/classes/QueueProcessor.php#L897).)

```
entryMessage() passing to parse()

INSIDE parse() BEFORE passing evaluate()

INSIDE parse() AFTER passing evaluate()

INSIDE parse() BEFORE passing evaluate()

INSIDE parse() AFTER passing evaluate()

INSIDE parse() BEFORE passing evaluate()

INSIDE parse() AFTER passing evaluate()

INSIDE parse() BEFORE passing evaluate()

INSIDE parse() AFTER passing evaluate()

INSIDE parse() BEFORE passing evaluate()

INSIDE parse() AFTER passing evaluate()

INSIDE parse() BEFORE passing evaluate()

INSIDE parse() AFTER passing evaluate()

INSIDE parse() BEFORE passing evaluate()
```

**Comment by raamdev** [comment]
The PHP it's choking on is somewhere in here: [`src/includes/templates/type-s/email/comment-notification/message.php`](https://github.com/websharks/comment-mail-pro/blob/160611-RC/src/includes/templates/type-s/email/comment-notification/message.php)

**Comment by raamdev** [comment]
This issue is making me wonder how difficult it would be a for a site owner to debug their own modified templates if they find something isn't working as expected...

**Comment by raamdev** [comment]
@jaswsinc Well, it looks like what I was suspecting with Template processing and `evaluate()` above may have been a false alarm. I wasn't able to reproduce it consistently and on subsequent cron runs the logs ended with `INSIDE parse() AFTER passing evaluate()`, as would be expected.

----

I'm taking a break from this for now, but I wanted to leave some notes with where I left off:

I'm currently focused on [`processEntry()`](https://github.com/websharks/comment-mail-pro/blob/160611-RC/src/includes/classes/QueueProcessor.php#L235), where I've added the following debugging routines:

```php
    protected function processEntry(\stdClass $entry)
    {
        if ($entry->dby_queue_id || $entry->logged) {
            return true; // Already processed this.
        }
        if (!($entry_props = $this->validatedEntryProps($entry))) {
            return true; // Bypass; unable to validate entry props.
        }
        if ($this->checkEntryHoldUntilTime($entry_props)) {
            return false; // Holding (for now).
        }
        $this->checkCompileEntryDigestableEntries($entry_props);

        file_put_contents(WP_CONTENT_DIR.'/cm-queue-debug.log', "AFTER checkCompile...()\n\n", FILE_APPEND);

        if (!($entry_headers = $this->entryHeaders($entry_props))) {
            $entry_props->event     = 'invalidated'; // Invalidate.
            $entry_props->note_code = 'comment_notification_headers_empty';

            $this->logEntry($entry_props); // Log invalidation.
            return true; // Not possible; headers are empty.
        }

        file_put_contents(WP_CONTENT_DIR.'/cm-queue-debug.log', "AFTER entryHeaders()\n\n", FILE_APPEND);

        if (!($entry_subject = $this->entrySubject($entry_props))) {
            $entry_props->event     = 'invalidated'; // Invalidate.
            $entry_props->note_code = 'comment_notification_subject_empty';

            $this->logEntry($entry_props); // Log invalidation.
            return true; // Not possible; subject line is empty.
        }

        file_put_contents(WP_CONTENT_DIR.'/cm-queue-debug.log', "AFTER entrySubject()\n\n", FILE_APPEND);

        if (!($entry_message = $this->entryMessage($entry_props))) {
            $entry_props->event     = 'invalidated'; // Invalidate.
            $entry_props->note_code = 'comment_notification_message_empty';
            file_put_contents(WP_CONTENT_DIR.'/cm-queue-debug.log', "BEFORE logEntry() AFTER entrySubject()\n\n", FILE_APPEND);

            $this->logEntry($entry_props); // Log invalidation.
            return true; // Not possible; message body is empty.
        }

        file_put_contents(WP_CONTENT_DIR.'/cm-queue-debug.log', "AFTER entryMessage()\n\n", FILE_APPEND);

        $entry_props->event     = 'notified'; // Notifying now.
        $entry_props->note_code = 'comment_notification_sent_successfully';

        file_put_contents(WP_CONTENT_DIR.'/cm-queue-debug.log', "REACHED NEAR END Of processEntry()\n\n", FILE_APPEND);

        $this->logEntry($entry_props); // Log successful processing.
        $this->plugin->utils_mail->send($entry_props->sub->email, $entry_subject, $entry_message, $entry_headers);
        return true; // Notified; OK to delete this entry now.
    }
```

With that in place (along with the original logging routine @jaswsinc suggested I add to make sure Cron was running), my log file contains the following:

```
Array
(
    [doing_wp_cron] => 1466052317.7762129306793212890625
)


AFTER checkCompile...()

AFTER entryHeaders()

AFTER entrySubject()
```

So as you can see, we never make it past this line:

```
if (!($entry_message = $this->entryMessage($entry_props))) {
```

Which tells me that something is going on inside `entryMessage()`.

Here's a copy of `$entry_props` being passed into the `entryMessage()` method itself:

```
stdClass Object
(
    [event] =>
    [note_code] =>
    [entry] => stdClass Object
        (
            [ID] => 1
            [sub_id] => 966
            [user_id] => 0
            [post_id] => 16860
            [comment_parent_id] => 11853
            [comment_id] => 11858
            [insertion_time] => 1465933066
            [last_update_time] => 1465933066
            [hold_until_time] => 0
            [dby_queue_id] => 0
            [logged] =>
        )

    [sub] => stdClass Object
        (
            [ID] => 966
            [key] => kevv9yco8s0zlf36fx6
            [user_id] => 0
            [post_id] => 16860
            [comment_id] => 0
            [deliver] => asap
            [fname] => Raam+test2allreplies
            [lname] =>
            [email] => raam+test2allreplies@raamdev.com
            [insertion_ip] =>
            [insertion_region] =>
            [insertion_country] =>
            [last_ip] =>
            [last_region] =>
            [last_country] =>
            [status] => subscribed
            [insertion_time] => 1465903656
            [last_update_time] => 1465932801
        )

    [sub_post] => WP_Post Object
        (
            [ID] => 16860
            [post_author] => 1
            [post_date] => 2015-08-06 12:57:46
            [post_date_gmt] => 2015-08-06 16:57:46
            [post_content] => Self-sufficiency fosters empathy.
            [post_title] => Empathy
            [post_excerpt] =>
            [post_status] => publish
            [comment_status] => open
            [ping_status] => open
            [post_password] =>
            [post_name] => empathy
            [to_ping] =>
            [pinged] =>
            [post_modified] => 2015-08-06 12:57:46
            [post_modified_gmt] => 2015-08-06 16:57:46
            [post_content_filtered] =>
            [post_parent] => 0
            [guid] => https://raam.org/?p=16860
            [menu_order] => 0
            [post_type] => post
            [post_mime_type] =>
            [comment_count] => 6
            [filter] => raw
        )

    [sub_comment] =>
    [post] => WP_Post Object
        (
            [ID] => 16860
            [post_author] => 1
            [post_date] => 2015-08-06 12:57:46
            [post_date_gmt] => 2015-08-06 16:57:46
            [post_content] => Self-sufficiency fosters empathy.
            [post_title] => Empathy
            [post_excerpt] =>
            [post_status] => publish
            [comment_status] => open
            [ping_status] => open
            [post_password] =>
            [post_name] => empathy
            [to_ping] =>
            [pinged] =>
            [post_modified] => 2015-08-06 12:57:46
            [post_modified_gmt] => 2015-08-06 16:57:46
            [post_content_filtered] =>
            [post_parent] => 0
            [guid] => https://raam.org/?p=16860
            [menu_order] => 0
            [post_type] => post
            [post_mime_type] =>
            [comment_count] => 6
            [filter] => raw
        )

    [comment] => WP_Comment Object
        (
            [comment_ID] => 11858
            [comment_post_ID] => 16860
            [comment_author] => secondreplytotest1
            [comment_author_email] => raam+secondreplytotest1@websharks-inc.com
            [comment_author_url] =>
            [comment_author_IP] => 97.101.220.142
            [comment_date] => 2016-06-14 15:37:18
            [comment_date_gmt] => 2016-06-14 19:37:18
            [comment_content] => 2nd Reply to Test 1
            [comment_karma] => 0
            [comment_approved] => 1
            [comment_agent] => Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36
            [comment_type] =>
            [comment_parent] => 11853
            [user_id] => 0
            [children:protected] =>
            [populated_children:protected] =>
            [post_fields:protected] => Array
                (
                    [0] => post_author
                    [1] => post_date
                    [2] => post_date_gmt
                    [3] => post_content
                    [4] => post_title
                    [5] => post_excerpt
                    [6] => post_status
                    [7] => comment_status
                    [8] => ping_status
                    [9] => post_name
                    [10] => to_ping
                    [11] => pinged
                    [12] => post_modified
                    [13] => post_modified_gmt
                    [14] => post_content_filtered
                    [15] => post_parent
                    [16] => guid
                    [17] => menu_order
                    [18] => post_type
                    [19] => post_mime_type
                    [20] => comment_count
                )

        )

    [props] => Array
        (
            [1] => stdClass Object
 *RECURSION*
        )

    [comments] => Array
        (
            [11858] => WP_Comment Object
                (
                    [comment_ID] => 11858
                    [comment_post_ID] => 16860
                    [comment_author] => secondreplytotest1
                    [comment_author_email] => raam+secondreplytotest1@websharks-inc.com
                    [comment_author_url] =>
                    [comment_author_IP] => 97.101.220.142
                    [comment_date] => 2016-06-14 15:37:18
                    [comment_date_gmt] => 2016-06-14 19:37:18
                    [comment_content] => 2nd Reply to Test 1
                    [comment_karma] => 0
                    [comment_approved] => 1
                    [comment_agent] => Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36
                    [comment_type] =>
                    [comment_parent] => 11853
                    [user_id] => 0
                    [children:protected] =>
                    [populated_children:protected] =>
                    [post_fields:protected] => Array
                        (
                            [0] => post_author
                            [1] => post_date
                            [2] => post_date_gmt
                            [3] => post_content
                            [4] => post_title
                            [5] => post_excerpt
                            [6] => post_status
                            [7] => comment_status
                            [8] => ping_status
                            [9] => post_name
                            [10] => to_ping
                            [11] => pinged
                            [12] => post_modified
                            [13] => post_modified_gmt
                            [14] => post_content_filtered
                            [15] => post_parent
                            [16] => guid
                            [17] => menu_order
                            [18] => post_type
                            [19] => post_mime_type
                            [20] => comment_count
                        )

                )

        )

    [held] =>
    [dby_queue_id] => 0
    [logged] =>
)
```

----

My brain is fried for now. Maybe you can see something I didn't, @jaswsinc. 😄

**Comment by jaswsinc** [comment]
@raamdev writes...

> So as you can see, we never make it past this line:
> if (!($entry_message = $this->entryMessage($entry_props))) {

Copy that. Awesome work in debugging this so far. So it looks to me like there is a fatal error in that file. That should leave behind something in your PHP error log. Although, it might not show you very much, since that code is being eval'd. Still, it should help you confirm that a fatal error is in fact taking place in eval'd code. Do you find anything in your PHP error log?

The next step I would take is to do the same thing you've been doing thus far with the debugging lines, but this time put them into the template file that is causing the problem and see if you can get closer to determining which line of code in the template is choking.

Referencing: https://github.com/websharks/comment-mail-pro/blob/000000-dev/src/includes/templates/type-s/email/comment-notification/message.php

Since this doesn't seem to impact everyone at all times, it could have something to do with a certain condition being met in that template file; e.g., the comment having a parent maybe.

**Comment by raamdev** [comment]
@jaswsinc writes...
> Do you find anything in your PHP error log?

No, no errors in the error log.

> The next step I would take is to do the same thing you've been doing thus far with the debugging lines, but this time put them into the template file that is causing the problem and see if you can get closer to determining which line of code in the template is choking.
> 
> Referencing: https://github.com/websharks/comment-mail-pro/blob/000000-dev/src/includes/templates/type-s/email/comment-notification/message.php

Done. It appears that things go wrong on [this line in `message.php`](https://github.com/websharks/comment-mail-pro/blob/160611-RC/src/includes/templates/type-s/email/comment-notification/message.php#L36), basically as soon as `$sub` or `$sub_post` are used. Maybe those are being referenced wrong??

**Comment by raamdev** [comment]
I did `print_r(get_defined_vars(), true)` in `message.php` and it seems that `$sub` and `$sub_post` are accounted for...

```
[...]
   [___vars] => Array
        (
            [event] =>
            [note_code] =>
            [entry] => stdClass Object
                (
                    [ID] => 3
                    [sub_id] => 966
                    [user_id] => 0
                    [post_id] => 16860
                    [comment_parent_id] => 11853
                    [comment_id] => 11862
                    [insertion_time] => 1466199965
                    [last_update_time] => 1466199965
                    [hold_until_time] => 0
                    [dby_queue_id] => 0
                    [logged] =>
                )

            [sub] => stdClass Object
                (
                    [ID] => 966
                    [key] => kevv9yco8s0zlf36fx6
                    [user_id] => 0
                    [post_id] => 16860
                    [comment_id] => 0
                    [deliver] => asap
                    [fname] => Raam+test2allreplies
                    [lname] =>
                    [email] => raam+test2allreplies@raamdev.com
                    [insertion_ip] =>
                    [insertion_region] =>
                    [insertion_country] =>
                    [last_ip] =>
                    [last_region] =>
                    [last_country] =>
                    [status] => subscribed
                    [insertion_time] => 1465903656
                    [last_update_time] => 1465932801
                )

            [sub_post] => WP_Post Object
                (
                    [ID] => 16860
                    [post_author] => 1
                    [post_date] => 2015-08-06 12:57:46
                    [post_date_gmt] => 2015-08-06 16:57:46
                    [post_content] => Self-sufficiency fosters empathy.
                    [post_title] => Empathy
                    [post_excerpt] =>
                    [post_status] => publish
                    [comment_status] => open
                    [ping_status] => open
                    [post_password] =>
                    [post_name] => empathy
                    [to_ping] =>
                    [pinged] =>
                    [post_modified] => 2015-08-06 12:57:46
                    [post_modified_gmt] => 2015-08-06 16:57:46
                    [post_content_filtered] =>
                    [post_parent] => 0
                    [guid] => https://raam.org/?p=16860
                    [menu_order] => 0
                    [post_type] => post
                    [post_mime_type] =>
                    [comment_count] => 7
                    [filter] => raw
                )

            [sub_comment] =>
            [post] => WP_Post Object
                (
                    [ID] => 16860
                    [post_author] => 1
                    [post_date] => 2015-08-06 12:57:46
                    [post_date_gmt] => 2015-08-06 16:57:46
                    [post_content] => Self-sufficiency fosters empathy.
                    [post_title] => Empathy
                    [post_excerpt] =>
                    [post_status] => publish
                    [comment_status] => open
                    [ping_status] => open
                    [post_password] =>
                    [post_name] => empathy
                    [to_ping] =>
                    [pinged] =>
                    [post_modified] => 2015-08-06 12:57:46
                    [post_modified_gmt] => 2015-08-06 16:57:46
                    [post_content_filtered] =>
                    [post_parent] => 0
                    [guid] => https://raam.org/?p=16860
                    [menu_order] => 0
                    [post_type] => post
                    [post_mime_type] =>
                    [comment_count] => 7
                    [filter] => raw
                )
[...]
```

**Comment by raamdev** [comment]
As I noted in Slack, what's really odd is that those two notifications that were stuck in the queue for a few days while I was initially testing this suddenly disappeared from the queue at some point over the last ~35 hours (the timestamp on _when_ they were actually sent is wrong—i.e., it looks like they were processed correctly from the start, when they most certainly were not). 

I posted another comment a few hours ago on the post that I'm using for testing and that generated two more notifications, which got stuck once again.

**Comment by raamdev** [comment]
One thing I did notice looking at the output of `print_r(get_defined_vars(), true)` in `message.php` was that the very first array key is `[___string]` that contains what looks like a full copy of the contents of `message.php`. I did some research and I haven't been able to find anything about what `[___string]` signifies. I even tried digging into the PHP source. 

```
Array
(
    [___string] => <?php
namespace WebSharks\CommentMail;

/*
 * @var Plugin           $plugin       Plugin class.
 * @var Template         $template     Template class.
 *
 * Other variables made available in this template file:
 *
 * @var string           $email_header Parsed email header template.
 * @var string           $email_footer Parsed email footer template.
 *
 * @var \stdClass        $sub          Subscription object data.
 *
 * @var \WP_Post         $sub_post     Post they're subscribed to.
 *
 * @var \WP_Comment|null $sub_comment  Comment they're subcribed to; if applicable.
 *
 * @var \WP_Comment[]    $comments     An array of all WP comment objects we are notifying about.
 *
 * -------------------------------------------------------------------
 * @note In addition to plugin-specific variables & functionality,
 *    you may also use any WordPress functions that you like.
 */
?>
<?php // Sets document <title> tag via `%%title%%` replacement code in header.
echo str_replace('%%title%%', __('Comment Notification(s)', 'comment-mail'), $email_header); ?>

<?php
file_put_contents(WP_CONTENT_DIR.'/cm-queue-debug.log', "message.php:30\n\n".print_r(get_defined_vars(), true), FILE_APPEND);
/*
 * Here we define a few more variables of our own.
 * All based on what the template makes available to us;
 * ~ as documented at the top of this file.
 */
// URL to comments on the post they're subscribed to.
$sub_post_comments_url = get_comments_link($sub_post->ID);
file_put_contents(WP_CONTENT_DIR.'/cm-queue-debug.log', "message.php:38\n\n", FILE_APPEND);
[...]
```

Something tells me that the way the PHP templates are being parsed/evaluated is causing the odd behavior I'm seeing, but I can't put my finger on why...

**Comment by raamdev** [comment]
9 hours 39 minutes after arriving in the Mail Queue, one of the "stuck" notifications went through. However, the other stuck notification, which was generated at the same time as the one that went through, is still sitting the Mail Queue.

I'm adding a few more things to my logging routines to hopefully get more information when the next time one goes through.

**Comment by jaswsinc** [comment]
Copy that. Thank you for the updates. The `___string` comes from this function. It might be worth us changing the way templates are parsed; i.e., moving from `eval()` to just `include()` in the future.

Referencing: https://github.com/websharks/comment-mail-pro/blob/160618/src/includes/classes/UtilsPhp.php#L71

**Comment by raamdev** [comment]
@jaswsinc The other two pending notifications in the queue eventually went through, but I mistakenly updated Comment Mail to the latest version and overwrote all the logging lines I had added to the codebase, so I wasn't able to catch any extra information.

Do you have any thoughts on why they would _eventually_ go through? That seems like a clue to me. If they go through _at all_, then it must not be a parsing issue (otherwise they would never go through) but instead something related to time...

**Comment by bobinoz** [comment]
Hi everybody

I just wondered if you are still working on this? I've got to the stage where I need to find a solution, because at the moment the front end user experience on my website is not great for my readers with lots of pages timing out after they make comments. I am now considering going through my subscribers on StCR and just randomly deleting some users (not ideal) from the system just to speed up things. Before I take that drastic action though, just wondered if there were any updates?

Thanks, Bob

**Comment by raamdev** [comment]
@bobinoz Yes, we're still working on this. It's a high-priority issue for the next release. I'll be digging into this issue this week.

**Comment by bobinoz** [comment]
Sounds good raamdev, and thanks for the quick response. I will hold fire on that subscriber cull then and wait to hear from you further. Thanks, Bob

**Comment by jaswsinc** [comment]
> That seems like a clue to me. If they go through at all, then it must not be a parsing issue (otherwise they would never go through) but instead something related to time...

If you believe it to be an issue with time, then it would almost certainly show up at this line; i.e., this would be a good place to begin another round of debugging. https://github.com/websharks/comment-mail-pro/blob/160618/src/includes/classes/QueueProcessor.php#L244

So for instance, if there are messages in the queue and you look in the DB and find that all criteria suggests that they _should_ be sent on the next queue process, but the next queue process runs, and they are _not_ sent, then it was almost certainly because of this line.

If not there, then [here](https://github.com/websharks/comment-mail-pro/blob/160618/src/includes/classes/QueueProcessor.php#L799), where the query either will or will not include them when processing begins.

---

I also wouldn't give up on the idea that it could be related to a parsing issue in the template file that is triggered by some special circumstance that I haven't seen yet.

It would be easier to debug this if templates were not being eval'd. In PHP 7, errors in `eval()` can be caught as an exception, so it's much easier. In older versions of PHP, eval'd code that triggers an error gives you very little to go on.

I feel it would be an improvement in Comment Mail if we stopped using `eval()` for template files, and instead `include()` them in an isolated way. So for instance, if you look at [this line](https://github.com/websharks/comment-mail-pro/blob/160618/src/includes/classes/Template.php#L149), you can see it currently calls upon `->evaluate()` and it passes a set of `$vars`.

That could be changed so that instead of calling `->evaluate()`, we call a method that would include the file, buffer the output, and return the result. No different than what we do now, but minus a call to `eval()`, which will improve compatibility, security, and make it easier to catch errors when they occur.

```php
function isolatedInclude($file_path, array $vars) {
    extract($vars);
    ob_start();
    include $file_path;
    return ob_get_clean();
}
```

**Comment by jaswsinc** [comment]
↑ That example could be cleaned up a bit. For instance, it would best to avoid polluting the currently defined variables with the function parameters themselves; i.e., `$file_path` and `$vars`. Those could renamed to something that could be less likely to conflict with what is extracted from `$vars`; e.g., `$___file_path`, `$___vars`.

**Comment by jaswsinc** [comment]
My feeling at the moment is that this is related to a template parsing issue that we haven't caught yet. Why? Because I went over the QueueProcessor class carefully about a month ago, did a video about it, and put some time into trying to debug it myself. If there's a bug related to time it would surprise me; i.e., I'm not seeing it.

That's not to say there's _not_ a bug. There very well could be. I'd just be surprised to see that be the case. For that matter, I haven't been able to reproduce this at all yet myself. However, based on the helpful reporting you've been doing here, it would seem more likely to me that it's a template parsing issue that results in an error, which shuts down the script in an unexpected way.

**Comment by bobinoz** [comment]
Hi everyone

Sorry to trouble you all again, but I noticed there was an update to this plug-in a short while ago. I assume, because there's been no update here, that this issue has not yet resolved?

So I wondered if you had any updates on this? Thanks again, Bob

**Comment by raamdev** [comment]
@bobinoz That's correct. The latest Comment Mail release did not include any changes from this issue, but this is still a high-priority issue and the next release will hopefully have this issue resolved.

**Comment by bobinoz** [comment]
Okay, thanks for the update, I do appreciate it.

**Comment by aptharsia** [comment]
Add me to the list of having this bug. Hope this is resolved soon. BTW, my database is over 26,000 subscriptions (not as in that's how many emails are being sent at once, just total.)

**Comment by raamdev** [comment]
@aptharsia Thanks for the feedback! This issue is still very much in progress and I'm hoping to get it closed for the next release.

**Comment by IvanRF** [comment]
@raamdev did you find a way to manually execute some PHP in order to process the `Queued (Pending) Notifications`?

**Comment by raamdev** [comment]
@IvanRF No, that's the main problem of this issue: Some **Queued (Pending) Notifications** are not getting processed as they should when the appropriate cron runs.

**Comment by IvanRF** [comment]
@raamdev and what about the database? in the first post you pointed to `Holding Until` = `n/a`. Where is that stored and could it help to change it?

**Comment by IvanRF** [comment]
I solved my issue 😃 

I started digging, tried chaning `hold_until_time` on the database, check the code and finally found with WP Control that the cron job `_cron_comment_mail_queue_processor` was not present. I missed that yesterday.

So, to solve it, I just runned on WP Control (**Add PHP Cron Event** option) this code I found in your code:
`
wp_clear_scheduled_hook('_cron_comment_mail_queue_processor');
wp_schedule_event(time() + 60, 'every5m', '_cron_comment_mail_queue_processor');
`

Now, the cron job is there and it is processing mails again.

**Comment by raamdev** [comment]
@IvanRF That's odd. There is no scenario in which the `_cron_comment_mail_queue_processor` cron event should ever get deleted (other than when you uninstall Comment Mail).

**Comment by IvanRF** [comment]
It will be useful to know if the other users having this issue have this cron job running or not.

The processing stopped 2 weeks ago, I think that at that time I was testing the plugin `Captcha by BestWebSoft` against `W3TC`, and had to disable Object cache in order to make the captcha work. I don't know if the middle of cleaning caches the cron job could be affected.

**Comment by bobinoz** [comment]
> It will be useful to know if the other users having this issue have this cron job running or not.

I would be happy to supply this information if someone could point me in the right direction to find out, although I do currently have Comment Mail deactivated.

**Comment by IvanRF** [comment]
@bobinoz you can use the `WP Crontrol` plugin and go to Cron Events; or if you have `Wordfence` go to Diagnostics > Cron Jobs.

**Comment by bobinoz** [comment]
Okay, I've installed WP Crontrol but of course the Cron job isn't showing, I have Comment Mail deactivated. If I activate it, then it will automatically deactivate StCR which I am currently using, so I'm a little concerned about the implications of that.

Advice needed; if I just quickly activate Comment Mail and then look in the Cron jobs should I be able to see it immediately? Once I know the answer to the question, if I then deactivate Comment Mail again will StCR automatically kick in again with no harm done?

**Comment by raamdev** [comment]
@bobinoz writes...

> Advice needed; if I just quickly activate Comment Mail and then look in the Cron jobs should I be able to see it immediately? 

Yes, it should appear immediately after Comment Mail is activated.

> Once I know the answer to the question, if I then deactivate Comment Mail again will StCR automatically kick in again with no harm done?

Yes, correct. Comment Mail won't touch the StCR data in any way. You can simply deactivate Comment Mail and then make sure StCR is enabled and you'll be back to the way you were.

**Comment by bobinoz** [comment]
Okay, I had a look at this today, and with Comment Mail deactivated I had the following to Cron jobs showing in the WP Crontrol plug-in:

_cron_comment_mail_sub_cleaner	None

_cron_comment_mail_log_cleaner	None

I then disabled StCR and enabled Comment Mail and looked inside the Cron job events again and found:

_cron_comment_mail_queue_processor	None	

_cron_comment_mail_sub_cleaner	None	

_cron_comment_mail_log_cleaner	None

I have now deactivated Comment Mail again and activated StCR and checked again in the Cron job list and the same three Cron jobs as above are still showing.

Hope that helps, thanks, Bob

**Comment by IvanRF** [comment]
@bobinoz what I can tell from that is that this plugin does not remove the cron jobs on deactivating, but more importantly that your original issue was the same as mine: `_cron_comment_mail_queue_processor` was not running.
Now, @raamdev told me this was fixed on v160618 (see #194). So, I guess that if this happened to you while running a previous version, you will have no issues with the latest version.

**Comment by raamdev** [comment]
@bobinoz Can you tell me which version of Comment Mail you ran that test with?

**Comment by bobinoz** [comment]
@raamdev Version 160824

**Comment by jaswsinc** [comment]
Flagging the objective in this issue, at least for part 1, as what was outlined here:
https://github.com/websharks/comment-mail/issues/192#issuecomment-234367442

Estimate at 1 day.

**Comment by raamdev** [comment]
@bobinoz Thank you.

@IvanRF My feeling is that the issue you reported with the cron job is unrelated to the core issue described and researched in this GitHub issue, which is related to the mystery that in some cases notifications get stuck in the Queued (Pending) state. If you feel there is an issue related to the cron job, please open a separate GitHub issue with a list of steps to reproduce the problem so that we can add that to the list of things that need research.

@jaswsinc writes...
> Flagging the objective in this issue, at least for part 1, as what was outlined here:
https://github.com/websharks/comment-mail/issues/192#issuecomment-234367442
>
> Estimate at 1 day.

Awesome. Thanks! I'm keeping this on the Next Release milestone so that we can get this long-standing issue fixed, hopefully once and for all! :-)

**Comment by jaswsinc** [comment]
Next Release Changelog:

- **Template Parsing:** When parsing templates, this release uses `include()` instead of `eval()` whenever possible. This improves compatibility with shared hosting providers and makes it easier to debug template parsing issues should they occur. See also [issue #192](https://github.com/websharks/comment-mail/issues/192) for further details.

**Comment by raamdev** [comment]
@jaswsinc You marked this as 'partial completion'; could you clarify? Is it 'partial' because it still needs to be tested to confirm the original issue has been resolved or are you suspecting it has not been resolved and more work will be needed once we get a chance to debug again?

**Comment by jaswsinc** [comment]
@raamdev Partial because this change only makes it easier for us to debug (i.e., discover) what is causing this problem on some installations. In short, the change documented for the next release does nothing to correct the problem, it only makes it easier for us to discover what may be causing it. As I understand it, none of us have been able to detect what actually causes this yet. My hope is that better template parsing will get us one step closer.

**Comment by raamdev** [comment]
I just ran the latest from the `dev` branch (which includes your latest changes to the way templates are parsed) and following [the steps I outlined above](https://github.com/websharks/comment-mail/issues/192#issuecomment-225998689), **I have been unable to reproduce the original issue** outlined here, i.e., messages are no longer being stuck in the queue! 

@lucashall @bobinoz @aptharsia @IvanRF If any of you would be open to testing this latest fix to see if it fixes the stuck "awaiting processing" notifications in the Mail Queue (assuming you were having this issue), that would be awesome. Send an email to raam at websharks-inc dot com and I'll send you a copy of the latest dev release. Please mention this thread in your email.

**Comment by bobinoz** [comment]
@raamdev   Yes, I'm happy to test it, and I've sent you an email.

**Comment by aptharsia** [comment]
Tried the dev release, still have the issue of notifications being stuck in processing mode and nothing gets sent.

**Comment by raamdev** [comment]
@aptharsia writes...
> Tried the dev release, still have the issue of notifications being stuck in processing mode and nothing gets sent.

Are these old notifications that were in the queue before installing the dev version of Comment Mail, or did you install the dev version and then generate some new notifications to see if they'd get stuck? (In my test, I generated new notifications and they didn't get stuck like they had in previous tests.) 

@bobinoz writes...
> Yes, I'm happy to test it, and I've sent you an email.

I replied to your email.

**Comment by aptharsia** [comment]
I cleared any notifications still waiting, enabled and generated new notifications that were never sent out.

**Comment by raamdev** [comment]
@aptharsia Thank you for testing and reporting your results. I'll need to run some more tests to see if I can reproduce this again. 

@bobinoz When you get the dev version of Comment Mail that I emailed you, it would be great to hear if you're still seeing this issue.

**Comment by bobinoz** [comment]
So I have installed Comment Mail and tested it briefly this afternoon, comments are still being held in the queued (pending) notifications area with the message 'n/a; awaiting processing'. However, they are getting sent, there just seems to be a long delay.

After I had installed and activated Comment Mail, I started answering comments on various pages with different numbers of subscribers. It sent out 76 emails immediately but then after that it started holding them in the queue for processing. What it seems to be doing since then is sending out little batches of emails every now and then at around 10 or 20 minute intervals. The most emails it seems to send out from the queue any one time is 21. Sometimes it is as few as 5. The maximum gap between sending them appears to be 30 minutes.

In the space of about seven hours, it has managed to send out all 363 emails in the queue which is now empty as it's late at night here and new comments have stopped coming in. If it were a busy day though, I can imagine the queue just building up until eventually it could take seven or eight hours before catching up with itself.

When I stopped answering comments, I think there were about 150 comments stuck in the queue, it has taken about three hours for those to slowly clear. So I'd say it's working now, but for some reason something is stopping it sending out all the comments at once. I am using SparkPost to deliver email, they do not have any hourly limits. As far as I'm aware, they just have a daily limit of 10,000 emails.

So if you have any clues how to fix it so they will get sent out immediately, we might be there.

I have noticed an unrelated problem as well, I hope you don't mind me mentioning it here. When I am logged in as admin but working on the front end, and I click on 'manage my subscriptions', with StCR I would see a list of subscribers for that particular post with tick boxes for them all so I could add, remove or delete them. When I click on 'manage my subscriptions' with Comment Mail, I don't see them at all, I just see that I am subscribed to all posts with my email address.

I can't find anywhere where I can view or amend subscriptions to a particular post or page. All I appear to be able to do is go to comment mail - subscriptions in the backend and view a complete list of subscribers. Is there anywhere I can go to quickly see all subscribers to a particular post or page?

Anyway, hope this information helps, and for now I am keeping Comment Mail activated. Thanks, Bob

**Comment by raamdev** [comment]
@bobinoz writes...
> So I'd say it's working now

Woohoo! That's great to hear! 

@bobinoz writes...
> for some reason something is stopping it sending out all the comments at once.

Have you reviewed the Queue Processor Adjustments panel to see if those settings are appropriate? **Comment Mail → Config. Options → Queue Processor Adjustments**. You probably need to adjust those settings so that more emails get sent out at once.


@bobinoz writes...
> I can't find anywhere where I can view or amend subscriptions to a particular post or page. All I appear to be able to do is go to comment mail - subscriptions in the backend and view a complete list of subscribers. Is there anywhere I can go to quickly see all subscribers to a particular post or page?

You can see a list of Comment Mail subscriptions for a post by editing the post itself and viewing the Comment Mail Meta Box, which will list all of the Comment Mail subscriptions associated with that post: 

![2016-11-10_13-28-55](https://cloud.githubusercontent.com/assets/53005/20189097/ae4c8240-a749-11e6-8c65-e4164bdf7e96.png)

Clicking "View All" at the bottom will bring you to the Comment Mail Subscriptions page, with the subscriptions filtered to just the subscriptions for that post.

**Comment by aptharsia** [comment]
Over about a 15 hour time span, 73 pending notifications only 12 were sent out. Many have been pending for over 12 hours. Nothing looks to be instant (or according to my settings) once moderator approved, for the 12 that got sent out, took 12 or so hours for the ones I timed. I wouldn't say it's fixed it so hope this issue will still be looked at.

**Comment by aptharsia** [comment]
Adding. The 12 that were sent has a 14 hour difference between the two sets sent yet there are 15 hour waits queued to be sent so it looks random on what gets sent and what queues for processing.

**Comment by raamdev** [comment]
@aptharsia Thank you for the additional information. I'll be keeping this issue open until I can run some more tests and get to the bottom of this. The [template parsing changes](https://github.com/websharks/comment-mail/issues/192#issuecomment-257944362) that Jason made related to this issue should help us with debugging. I just need to work at reproducing this issue in a test install because my test install that previously wasn't working is now suddenly working, so I need to keep testing.

**Comment by jaswsinc** [comment]
@aptharsia After the recent changes in this issue, what we are now looking for to diagnose the _why_, are your PHP error logs. If you can check with your hosting company or already have access to these logs, that would be much appreciated.

To clarify, with the improved template parsing as of late, we'd like to inspect any PHP errors being reported when this occurs, as that could shed light on a real solution; i.e., help us understand under what conditions this occurs and what error causes the queue to get stuck.

I have followed the steps that you outlined on a few different occasions now, and have been unable to reproduce. So whatever causes this remains a mystery for now. Until we can see PHP error logs that might unveil the underlying cause, I'm afraid this could remain open.

If you check your PHP error logs and find nothing, we'd like to know that also.

**Comment by bobinoz** [comment]
@raamdev Thanks for the information, yes, I can now see where I can view and amend subscriptions associated with particular posts and pages.

I've also check the settings you mention **Comment Mail → Config. Options → Queue Processor Adjustments**, but cannot make changes as that's only available in the pro version. However, the settings seem good to me, if I am reading it correctly it should send 100 emails at a time and do that every five minutes.

![cm4](https://cloud.githubusercontent.com/assets/19678956/20267240/7f002e5e-aac5-11e6-85a4-716a3aa0b75e.JPG)

Any idea why it isn't able to do that?

**Comment by raamdev** [comment]
@bobinoz Please open a separate GitHub issue for that, so that we don't go off topic in this one.

**Comment by aptharsia** [comment]
Is the _cron_comment_mail_queue_processor in WP Cron suppose to have a hook or argument or is that suppose to be blank? I've been watching the PHP error logs but nothing has shown since the last run 5 hours ago.

**Comment by raamdev** [comment]
@aptharsia There are no arguments, no. See screenshot below from WP Crontrol:

![2016-11-14_19-13-17](https://cloud.githubusercontent.com/assets/53005/20288031/7530581c-aa9e-11e6-83a9-5093468ad1c7.png)

**Comment by aptharsia** [comment]
23 hours since last notifications sent, the rest are still in the queue. Nothing is on the error log so far, does that mean it's not even trying to send them all this time?

**Comment by aptharsia** [comment]
I spoke too soon. It finally did another batch after 24 hours. I checked the error log and no errors for this plugin. Yesterday it did it twice with 25 minutes between the two batches and then nothing until 24 hours later.

**Comment by raamdev** [comment]
@aptharsia Could it be that the notifications were notifications that were part of a Daily Digest subscription that were _supposed_ to be held for 24 hours?

**Comment by renzms** [comment]
@raamdev 

Was unable to reproduce original issue. Notifications eventually sent in batches.

**Comment by aptharsia** [comment]
@raamdev Not this many.

**Comment by raamdev** [comment]
@aptharsia Thanks for the continued updates.

@jaswsinc Anything come to mind when you review the reports from @aptharsia above? Maybe we need some more detailed logging routines to help diagnose this issue for site owners that seem to have issues with notifications being sent irregularly?

**Comment by raamdev** [comment]
@aptharsia I just noticed that @bobinoz opened a separate GitHub issue explaining the same sort of irregular notification behavior; could you please post further updates about that in that other GitHub issue so that we can keep better track of this? See https://github.com/websharks/comment-mail/issues/317

@jaswsinc If you could post your thoughts over in https://github.com/websharks/comment-mail/issues/317 instead of here, that would be better. I think the core issue described here, with pending notifications _never_ being sent, has been resolved after changing the way templates are parsed. Now the issue seems to be more about _when_ notifications are sent.

This GitHub issue is getting really long and I think it's starting to stray from the issue that was originally reported, so I'd like to redirect things to https://github.com/websharks/comment-mail/issues/317 so that I can close this issue as of the next release.

**Comment by jaswsinc** [comment]
@aptharsia Thank you.

@raamdev Copy that. I followed up in https://github.com/websharks/comment-mail/issues/317#issuecomment-261170566

**Comment by raamdev** [comment]
**Comment Mail v161118** has been released and includes changes from this GitHub Issue. See the [v161118 announcement](http://comment-mail.com/comment-mail-v161118-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#192).
